name: Build Windows

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        
    - name: Install dependencies
      run: |
        # 安装必要的依赖
        choco install -y git cmake ninja libusb
        # 安装readline (通过MSYS2)
        choco install -y msys2
        $msys2Path = "C:\tools\msys64\usr\bin\bash.exe"
        & $msys2Path -lc "pacman -S --noconfirm mingw-w64-x86_64-readline"
        
    - name: Clone and build Proxmark3 CLI
      run: |
        Write-Host "Cloning Proxmark3 repository..."
        git clone --depth 1 https://github.com/Proxmark/proxmark3.git
        cd proxmark3
        
        Write-Host "Checking repository structure:"
        Get-ChildItem | Format-Table Name
        
        if (-not (Test-Path "CMakeLists.txt")) {
          Write-Error "CMakeLists.txt not found in proxmark3 directory"
          exit 1
        }
        
        Write-Host "Creating build directory..."
        mkdir build
        cd build
        
        Write-Host "Running CMake..."
        cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release `
          -DREADLINE_INCLUDE_DIR=C:/tools/msys64/mingw64/include `
          -DREADLINE_LIBRARY=C:/tools/msys64/mingw64/lib/libreadline.dll.a
          
        if ($LASTEXITCODE -ne 0) { 
          Write-Error "CMake failed"
          exit 1 
        }
        
        Write-Host "Building Proxmark3..."
        cmake --build .
        
        if ($LASTEXITCODE -ne 0) { 
          Write-Error "Build failed"
          exit 1 
        }
        
        $clientPath = "$env:GITHUB_WORKSPACE\proxmark3\build\client\proxmark3.exe"
        if (-not (Test-Path $clientPath)) {
          Write-Error "proxmark3.exe not found at $clientPath"
          exit 1
        }
        
        echo "PROXMARK_PATH=$clientPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        
    - name: Build GUI
      run: |
        # 修改代码中的路径
        (Get-Content proxmark3.cpp) -replace '"proxmark3.exe"', "`"$env:PROXMARK_PATH`"" | Set-Content proxmark3.cpp
        
        Write-Host "Running qmake..."
        qmake -spec win32-msvc
        
        if ($LASTEXITCODE -ne 0) { 
          Write-Error "qmake failed"
          exit 1 
        }
        
        Write-Host "Building GUI..."
        nmake release
        
        if ($LASTEXITCODE -ne 0) { 
          Write-Error "nmake failed"
          exit 1 
        }
        
        if (-not (Test-Path "release\Proxmark3GUI.exe")) {
          Write-Error "Proxmark3GUI.exe not found in release directory"
          exit 1
        }
        
    - name: Package
      run: |
        mkdir package
        copy release\Proxmark3GUI.exe package\
        copy $env:PROXMARK_PATH package\
        copy "C:\Program Files\LibUSB-Win32\bin\libusb0.dll" package\
        
        Write-Host "Running windeployqt..."
        windeployqt --release --force package\Proxmark3GUI.exe
        
        Write-Host "Creating archive..."
        7z a Proxmark3GUI-Windows.zip .\package\*
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Proxmark3GUI-Windows
        path: Proxmark3GUI-Windows.zip
        retention-days: 30
        
    - name: Debug build directory
      if: failure()
      run: |
        Write-Host "=== Current directory contents ==="
        Get-ChildItem -Recurse | Format-Table Name, Length, LastWriteTime
        Write-Host "=== Environment variables ==="
        Get-ChildItem Env: | Format-Table Name, Value
